<a href="https://colab.research.google.com/github/MaicolLojano/Mineria-de-Datos/blob/main/TP1/Lectura_ficheros_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**texto en negrita**<!--Header-->
<div>
    <div class="row" style="color: #4D4D4D;font-size: 15px;padding-bottom: 20px">
        <div class="col-md-7">
            <img src="" alt="Logo TECAZUAY" width="100%" class="img-responsive" style="margin:20px 0px 0px">
        </div>
        <div class="col-md-5">
            <h1 style="margin:15px 0px 0px;font-size: 40px;">Lectura y escritura de Fichero de Datos</h1>
            <div style="text-align:left;margin-top: 5px;"></div>
        </div>
    </div>
    <div class="row" style="background: #FCB517;padding: 10px 20px;">
        <div class="col-md-6">
            <div>CICLO: M3A</div>
        </div>
        <div class="col-md-6">
            <div style="text-align:right;">Autor: Verónica Chimbo <span style="margin-left: 30px;"></span></div>
        </div>
        <div style="text-align:right;">Carrera: TECNOLOGÍA SUPERIOR EN BIG DATA <span style="margin-left: 30px;"></span></div>
         <div style="text-align:right;">Estudiante: Maicol Lojano  <span style="margin-left: 30px;"></span></div>
          <div style="text-align:right;">Fecha: 10/06/2024  <span style="margin-left: 30px;"></span></div>
        </div>
    </div>
</div>
<!--/Header-->

# Introducción

La exporación, manipulación, visualización y análisis de datos empieza con la carga de los datos desde diferentes formatos de ficheros. En esta actividad veremos cómo leer ficheros de tipo `CSV`, `Excel`, `TXT`, `JSON` i `ZIP`, cargarlos en un `DataFrame` y volverlos a guardar en otro fichero.


![pandas_logo.png]()
Usaremos un paquete de `Python` llamado `pandas`, que facilita la manipulación y el análisis de datos. `Pandas` incorpora estructuras de datos rápidas y flexibles diseñadas para trabajar de una manera intuitiva con datos relacionales o etiquetados.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

Lo primero que haremos será importar la librería `pandas`.

In [ ]:
import pandas as pd

## Ficheros CSV

El acrónimo `CSV` corresponde a _Comma Separated Values_, es decir, ficheros separados por comas. De hecho, veremos que la función de `pandas` que usaremos para leer este tipo de ficheros también sirve para leer ficheros separados por otros caracteres, como los `TSV` o _Tab-Separated Values_, o los ficheros separados por punto y coma.

El fichero `CSV` que leeremos corresponde al dataset de la competición [Titanic: Machine Learning from Disaster](https://www.kaggle.com/c/titanic) de [Kaggle](https://www.kaggle.com/).

Para leer un fichero `CSV` usaremos la función [`read_csv`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html) de `pandas`.

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Actividad 2/data/titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Si el fichero no tiene cabecera, especificaremos el parámetro `header=None` y opcionalmente, el nombre de las columnas.

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Actividad 2/data/titanic_no_header.csv", header = None,
                 names = ["PassengerId", "Survived", "Pclass", "Name",
                          "Sex", "Age", "SibSp", "Parch", "Ticket", "Fare", "Cabin", "Embarked"
                         ])
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Com podemos ver, el resultado es exactamente el mismo, y la única diferencia es que le hemos tenido que especificar explícitament el nombre de las columnas.

Si queremos leer un fichero que no está separado por comas, especificaremos el separador con el parámetro `sep`.

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Actividad 2/data/titanic.csv", sep='\t')
df.head()

  PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0  1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/...
1  2,1,1,"Cumings, Mrs. John Bradley (Florence Br...
2  3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,S...
3  4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May ...
4  5,0,3,"Allen, Mr. William Henry",male,35,0,0,3...

Para volverlo a guardar en otro fichero, por ejemplo separado por punto y coma, usaremos la función [`to_csv`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html) de `pandas`.

In [ ]:
df.to_csv('titanic_semicolon.csv', sep=';')

Si intentamos volver a cargar desde el fichero que hemos creado justo ahora, veremos que nos ha creado una columna `Unnamed`. Esto pasa porque por defecto nos guarda el índice del `DataFrame`.

In [ ]:
pd.read_csv('/content/titanic_semicolon.csv', sep=';').head()

,Unnamed: 0,"PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked"
0,0,"1,0,3,""Braund, Mr. Owen Harris"",male,22,1,0,A/..."
1,1,"2,1,1,""Cumings, Mrs. John Bradley (Florence Br..."
2,2,"3,1,3,""Heikkinen, Miss. Laina"",female,26,0,0,S..."
3,3,"4,1,1,""Futrelle, Mrs. Jacques Heath (Lily May ..."
4,4,"5,0,3,""Allen, Mr. William Henry"",male,35,0,0,3..."

Para evitarlo, le explicitaremos que no quremos que nos guarde el índice mediante el parámetro `index=False`.

In [ ]:
df.to_csv('titanic_semicolon_no_index.csv', sep=';', index=False)

##  Ficheros Excel

Aún y ser un software propietario, `Excel` es una de las herramientas más populares y usadas en el tratamiento de datos. `Pandas` es capaz de leer los ficheros que genera este software en sus diferentes versiones.

El fichero `Excel` que leeremos corresponde al dataset de la competición [TMDB 5000 Movie Dataset](https://www.kaggle.com/tmdb/tmdb-movie-metadata) de [Kaggle](https://www.kaggle.com/). Este `Excel` tiene tres `sheets` que corresponden a las películas de los años `1900s`, `2000s` i `2010s`.

Para leer un fichero `Excel` usaremos la función [`read_excel`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html) de `pandas`.

In [ ]:
xls_file = pd.read_excel('/content/drive/MyDrive/Actividad 2/data/movies.xls')
xls_file.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,Intolerance: Love's Struggle Throughout the Ages,1916,Drama|History|War,NaN,USA,Not Rated,123,1.33,385907.0,NaN,...,436,22,9.0,481,691,1,10718,88,69.0,8.0
1,Over the Hill to the Poorhouse,1920,Crime|Drama,NaN,USA,NaN,110,1.33,100000.0,3000000.0,...,2,2,0.0,4,0,1,5,1,1.0,4.8
2,The Big Parade,1925,Drama|Romance|War,NaN,USA,Not Rated,151,1.33,245000.0,NaN,...,81,12,6.0,108,226,0,4849,45,48.0,8.3
3,Metropolis,1927,Drama|Sci-Fi,German,Germany,Not Rated,145,1.33,6000000.0,26435.0,...,136,23,18.0,203,12000,1,111841,413,260.0,8.3
4,Pandora's Box,1929,Crime|Drama|Romance,German,Germany,Not Rated,110,1.33,NaN,9950.0,...,426,20,3.0,455,926,1,7431,84,71.0,8.0

Nuestro `Excel` tiene tres `sheets`. Si no le decimos nada, por defecto la función [`read_excel`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_excel.html) nos carga el primero. Si queremos especificar otro, lo podemos hacer por el nombre mediante el parámetro `sheet_name`.

In [ ]:
xls_file = pd.read_excel('/content/drive/MyDrive/Actividad 2/data/movies.xls', sheet_name='2010s')
xls_file.head()

,Title,Year,Genres,Language,Country,Content Rating,Duration,Aspect Ratio,Budget,Gross Earnings,...,Facebook Likes - Actor 1,Facebook Likes - Actor 2,Facebook Likes - Actor 3,Facebook Likes - cast Total,Facebook likes - Movie,Facenumber in posters,User Votes,Reviews by Users,Reviews by Crtiics,IMDB Score
0,127 Hours,2010.0,Adventure|Biography|Drama|Thriller,English,USA,R,94.0,1.85,18000000.0,18329466.0,...,11000.0,642.0,223.0,11984,63000,0.0,279179,440.0,450.0,7.6
1,3 Backyards,2010.0,Drama,English,USA,R,88.0,NaN,300000.0,NaN,...,795.0,659.0,301.0,1884,92,0.0,554,23.0,20.0,5.2
2,3,2010.0,Comedy|Drama|Romance,German,Germany,Unrated,119.0,2.35,NaN,59774.0,...,24.0,20.0,9.0,69,2000,0.0,4212,18.0,76.0,6.8
3,8: The Mormon Proposition,2010.0,Documentary,English,USA,R,80.0,1.78,2500000.0,99851.0,...,191.0,12.0,5.0,210,0,0.0,1138,30.0,28.0,7.1
4,A Turtle's Tale: Sammy's Adventures,2010.0,Adventure|Animation|Family,English,France,PG,88.0,2.35,NaN,NaN,...,783.0,749.0,602.0,3874,0,2.0,5385,22.0,56.0,6.1

Para volverlo a guardar en otro fichero `Excel` usaremos la función  [`to_excel`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_excel.html) de `pandas`.

In [ ]:
xls_file.to_excel('/content/movies.xls.xlsx', index=False)

## Ficheros TXT

A veces los ficheros de datos no estan separados por ningún caracter en concreto, sino que cada campo tiene una medida fija. Estos tipos de ficheros se llaman _Fixed Width Format_, o de campos de ancho fija. La función [`read_fwf`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_fwf.html) de `pandas` nos permite tratar con estos ficheros. Si no especificamos el ancho de los campos, intentará inferir la estructura del fichero.

Los datos que usaremos son los [_ratings_](https://ratings.fide.com/download.phtml) de los jugadores de la Federación Internacional de Ajedrez.

In [ ]:
df = pd.read_fwf('/content/drive/MyDrive/Actividad 2/data/players_list_foa.txt')
df.head()

,ID Number,Name,Fed,Sex,Tit,WTit,OTit,FOA,SRtng,SGm,SK,RRtng,RGm,Rk,BRtng,BGm,BK,B-day,Flag
0,10224084,"A B M Hasibuzzaman, Tapan",BAN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1977,NaN
1,35077023,A Chakravarthy,IND,M,NaN,NaN,NaN,NaN,1151.0,0.0,40.0,NaN,NaN,NaN,NaN,NaN,NaN,1986,i
2,10207538,"A E M, Doshtagir",BAN,M,NaN,NaN,NaN,NaN,1840.0,0.0,40.0,1836.0,0.0,20.0,1860.0,0.0,20.0,1974,i
3,5716365,"A Hamid, Harman",MAS,M,NaN,NaN,NI,NaN,NaN,NaN,NaN,1593.0,0.0,20.0,NaN,NaN,NaN,0,NaN
4,10207546,"A K M Aminul, Islam",BAN,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN

## Ficheros JSON

`JSON`, acrónimo de _JavaScript Object Notation_, es un formato estándard de transferencia de datos que utiliza una sintaxi legible para los humanos y que consiste en listas anidadas de pares clave/valor. Por [ejemplo](http://json.org/example.html), aquí podemos ver un registro de una base de datos no relacional en formato JSON:

```json
{
  "menu": {
    "id": "file",
    "value": "File",
    "popup": {
      "menuitem": [
        {"value": "New", "onclick": "CreateNewDoc()"},
        {"value": "Open", "onclick": "OpenDoc()"},
        {"value": "Close", "onclick": "CloseDoc()"}
      ]
    }
  }
}
```

Como podemos ver, los datos no están estructurados en formato tabla. Cuando carguemos el `JSON` a un `DataFrame` con `pandas`, cada columna corresponderá a una de las claves de primer nivel de cada registro. Y su valor será, en el caso de listas anidadas, una lista en formato `JSON`.

Los datos que usaremos corresponden a los últimos 15 `issues` del paquete `pandas` publicados en [`Github`](https://api.github.com/repositories/858127/issues?per_page=15). Vemos que `pandas` también nos permite leer el fichero a través de su `URL`.

In [ ]:
df = pd.read_json('https://api.github.com/repositories/858127/issues?per_page=15')
df = pd.read_json('/content/drive/MyDrive/Actividad 2/data/pandas_issues.json')
df.head()

,url,repository_url,labels_url,comments_url,events_url,html_url,id,number,title,user,...,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,pull_request,body
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/20015,302742972,20015,DOC: enable matplotlib plot_directive to inclu...,"{'login': 'jorisvandenbossche', 'id': 1020496,...",...,NaN,[],None,0,2018-03-06 15:20:53+00:00,2018-03-06 15:21:59+00:00,NaT,OWNER,{'url': 'https://api.github.com/repos/pandas-d...,This adds the matplotlib.sphinxext.plot_direct...
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20014,302667311,20014,CLN: followons to refactor of series/test_inde...,"{'login': 'jreback', 'id': 953992, 'avatar_url...",...,NaN,[],{'url': 'https://api.github.com/repos/pandas-d...,1,2018-03-06 11:40:05+00:00,2018-03-06 12:14:41+00:00,NaT,CONTRIBUTOR,NaN,"xref #18614 \r\n\r\n- [ ] remove the classes,..."
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20012,302662325,20012,Center rolling window with date NotImplemented...,"{'login': 'weber-s', 'id': 25247745, 'avatar_u...",...,NaN,[],None,0,2018-03-06 11:22:54+00:00,2018-03-06 11:22:54+00:00,NaT,NONE,NaN,"#### Code Sample, a copy-pastable example if p..."
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20011,302656554,20011,WARN: numpy warnings on operations,"{'login': 'jreback', 'id': 953992, 'avatar_url...",...,NaN,[],{'url': 'https://api.github.com/repos/pandas-d...,0,2018-03-06 11:03:58+00:00,2018-03-06 11:06:37+00:00,NaT,CONTRIBUTOR,NaN,```\r\npandas/tests/frame/test_operators.py::T...
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20008,302516428,20008,to_latex shifts column names if MultiIndex con...,"{'login': 'toobaz', 'id': 1224492, 'avatar_url...",...,NaN,[],None,0,2018-03-06 00:24:20+00:00,2018-03-06 08:23:49+00:00,NaT,CONTRIBUTOR,NaN,"#### Code Sample, a copy-pastable example if p..."

En el `DataFrame` anterior vemos que hay campos, `milestone`, `pull_request` o `user`, que tienen como valor un otro `JSON`. Hay una manera de aplanar la estructura de un `JSON` para adaptarla en formato `DataFrame`, y es a través de la función [`json_normalize`](http://pandas.pydata.org/pandas-docs/version/0.19/generated/pandas.io.json.json_normalize.html).

In [ ]:
!pip install --upgrade pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Collecting pandas
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 35.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: pandas
  Attempting uninstall: pandas
    Found existing installation: pandas 2.0.3
    Uninstalling pandas-2.0.3:
      Successfully uninstalled pandas-2.0.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 2.2.2 which is incompatible.
google-colab 1.0.0 requires pandas==2.0.3, but you have pandas 2.2.2 which is incompatible.
Successfully installed pandas-2.2.2

In [ ]:
import json
import pandas as pd


with open('/content/drive/MyDrive/Actividad 2/data/pandas_issues.json') as f:
    issues = json.load(f)

df = pd.json_normalize(issues)
df.head()

,url,repository_url,labels_url,comments_url,events_url,html_url,id,number,title,labels,...,milestone.creator.received_events_url,milestone.creator.type,milestone.creator.site_admin,milestone.open_issues,milestone.closed_issues,milestone.state,milestone.created_at,milestone.updated_at,milestone.due_on,milestone.closed_at
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/20015,302742972,20015,DOC: enable matplotlib plot_directive to inclu...,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20014,302667311,20014,CLN: followons to refactor of series/test_inde...,"[{'id': 211029535, 'url': 'https://api.github....",...,https://api.github.com/users/jreback/received_...,User,False,134.0,1076.0,open,2017-10-20T10:17:09Z,2018-03-06T13:32:20Z,2018-03-31T07:00:00Z,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20012,302662325,20012,Center rolling window with date NotImplemented...,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20011,302656554,20011,WARN: numpy warnings on operations,"[{'id': 76865106, 'url': 'https://api.github.c...",...,https://api.github.com/users/jreback/received_...,User,False,134.0,1076.0,open,2017-10-20T10:17:09Z,2018-03-06T13:32:20Z,2018-03-31T07:00:00Z,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/20008,302516428,20008,to_latex shifts column names if MultiIndex con...,[],...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Vemos que ahora los campos ya no contienen listas de valores. Y es que el campo `user`, por ejemplo, se nos ha convertido en los camps `user.id`, `user.login`, `user.organizations_url`, `user.received_events_url`, `user.repos_url`, `user.site_admin`, `user.starred_url`, `user.subscriptions_url`, `user.type` y `user.url`.

Finalmente, para guardar el nuevo `DataFrame` aplanado en un fichero `JSON` usaremos la funció  [`to_json`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_json.html) de `pandas`.

In [ ]:
df.to_json('/content/drive/MyDrive/Actividad 2/data/pandas_issues_flattened.json')

## Ficheros zip

Cualquier de los formatos anteriores los podemos encontar comprimidos. Podemos descomprimir el fichero y después leerlo.

In [ ]:
import zipfile

zf = zipfile.ZipFile('/content/drive/MyDrive/Actividad 2/data/titanic.zip')
df = pd.read_csv(zf.open('titanic.csv'))
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Pero también podemos hacerlo todo en un solo paso sin tenerlo que descomprimir antes, con el parámetro `compression`.

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Actividad 2/data/titanic.zip', compression='zip')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**CONCLUSIONES**

En conclusión, para leer ficheros de datos, primero se utilizó from google.colab import drive para conectar con Google Drive. La exploración, manipulación, visualización y análisis de datos comienzan con la carga de datos desde distintos tipos de archivos como CSV, Excel, TXT, JSON y ZIP, los cuales se cargan en una estructura llamada DataFrame y luego se pueden guardar nuevamente en otro archivo. Los archivos CSV son ideales para datos tabulares, Excel para datos en varias hojas, TXT para texto simple, JSON para datos estructurados, y ZIP para comprimir archivos. Como observamos trabajar con estos formatos permite filtrar, agrupar y visualizar datos, y guardar los resultados facilita su reutilización y colaboración en futuros proyectos.